text = "FINAL QUESTION. PROVIDE THE SOLUTION TO THE PROBLEM, INCLUDE THE TRIPLE AFFIRMATIVE (1. SOLUTION HAS BEEN FOUND 2. SOLUTION IS PORTABLE 3. TECHNICAL IMPLEMENTATION IS POSSIBLE AND GENERALLY APPLICABLE)"
Answers = []
hell = true